### ISSUE TITLE
[REQ] RoShade Linux Support

### ISSUE THREAD

**Issue by imskyyc** [bituq/Roshade#12]
**Is your feature request related to a problem? Please describe.**
RoShade (and also ReShade) does not work at all on Linux, even after extensive troubleshooting, and using winetricks to install the correct DLLs. I have tried both the GitHub version as well as the version directly downloaded from the RoShade website

**Describe the solution you'd like**
I'd like to see RoShade support for Linux. Currently it is possible to get the RoShade UI in-game by copying a normal RoShade installation from a Windows installation on another drive, but ALL effects fail to compile.

**Describe alternatives you've considered**
I've looked on Reddit for alternatives to ReShade and/or RoShade, but none come close due to ReShade not working on Roblox by itself, and implementing ReShade or any equivalents in to Roblox does not work.

**Additional context**
None.

**Comment by bituq** [comment]
Hi, this is an injector related issue. Please head over to the [Reshade repository](https://github.com/crosire/reshade) and address the issue there.

**Comment by Ednaordinary** [comment]
@imskyyc Have you tried installing the windows DLL d3dcompiler_47? This solved it for me for almost all the effects, about 5 still not compiling but also effects I do not want to use
