### ISSUE TITLE
[REQ]macOS support

### ISSUE THREAD

**Issue by scratchusernamemrtbts** [bituq/Roshade#13]
**Is your feature request related to a problem? Please describe.**
I wanna use roshade on my mac bc I don’ have window and yes ik Bootcamp exist but I think it would be pretty cool if it supports mac (or even Linux)
**Describe the solution you'd like**
maybe is there a way to compile the source code to work with mac?
**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by bituq** [comment]
Hi, mac OS support will not be on the roadmap for as long as [Reshade](https://github.com/crosire/reshade) is incompatible. As far as I've interpreted from Crosire, this won't happen any time soon due to the complexity.
