### ISSUE TITLE
[REQ] How do I use this on Linux?

### ISSUE THREAD

**Issue by thesonicfan192** [bituq/Roshade#22]
**Is your feature request related to a problem? Please describe.**
I'd love to use this on Linux, but I am unsure if it works, or how to if it is possible.

**Describe the solution you'd like**
Please add support for Linux by looking into the home folder, and please add a guide on how to do it.

**Describe alternatives you've considered**
Maybe just provide the files so it is possible to be down manually.

**Additional context**
This would be useful, and I am sure it is possible, thank you for reading this.

**Comment by bituq** [comment]
I'm sorry, but Roshade is not compatible for Linux. This is an issue for the Reshade repository, as Roshade is just an installer for Reshade. You might want to post this request in the Reshade repository for further consideration.
