### ISSUE TITLE
RoShade violates several OS licenses.

### ISSUE THREAD

**Issue by ProjectHSI** [bituq/Roshade#25]
Simple as that, the violations are as follows:
Radegast - Violates GPL V2.0 license. (RoShade Pro, which is proprietary.) (Is this even used?)
Pascal Gilcher / qUINT - All rights reserved. This means you can't do anything with it unless you have permission, feel free to clarify below.
Daodan - Violates BSD 3-Clause, you must provide that license described in Daodan as part of your third-party acknowledgements. This one technically could be passed as a loophole because you don't provide the binaries, your computer downloads them, this depends on your defenition of "redistribution."
Reshade (!) - Violates BSD-3 Clause. see above. Unfortunately no loophole this time. You provde the DLL inside the installer.

Unfortunately if you don't want to modify the pack you have to abide by these licenses, feel free to comment on this.

**Comment by bituq** [comment]
Hello. As for qUINT, Pascal has granted me permission. Crosire and I have also communicated on the subject of what is defined as a "redistribution", and have agreed that the method at which Roshade uses Reshade is not in conflict with any of the license's terms. Note that there is a distinction between Roshade and Reshade, where the Roshade installer is its own software, and the Reshade DLL maintains its own license which is still accessible in its own implementation.

The other shaders are directly installed from their respective open-source repositories including their licenses, which is not in combat with their terms.

**Comment by ProjectHSI** [comment]
Ahh right, I see.
Unfortunately I'm unsure about Roshade not violating the BSD 3-Clause license for Reshade; the BSD 3-Clause states this:
`1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.`
Am I missing something?

**Comment by ProjectHSI** [comment]
Also what license are you using? Are you using a proprietary one or is it not included in Github's table?

**Comment by bituq** [comment]
As I mentioned earlier, the Reshade binary that is included in the installer contains the appropriate license.

**Comment by bituq** [comment]
The license that I use is a custom MIT license.

**Comment by ProjectHSI** [comment]
I'll close this issue as it seems to not violate any licenses, but mind telling me where you store the Reshade License? I can't find it.

**Comment by bituq** [comment]
Navigate to the 'About' tab in the Reshade menu.

**Comment by ProjectHSI** [comment]
ohhhh ok i see
i was expected somewhere with in the installer, never thought in reshade itself
