### ISSUE TITLE
update it to 64bit

### ISSUE THREAD

**Issue by dimalab726** [bituq/Roshade#33]
this thing doesnt work

**Comment by itBlanket** [comment]
That is because Roblox removed the 32 bit version of Roblox, which was the only version that didn't have Byfron.

Roshade needs to inject into Roblox in order to load the shaders, which Byfron doesn't like.

I don't know if a workaround will be found.

**Comment by bituq** [comment]
We have tested this thoroughly and the 64-bit version of reshade doesn't work either, even when signed.

**Comment by ryoojiz** [comment]
apparently, a common workaround for programs that still require 32-bit roblox is to do so via the microsoft store version of roblox, although I don't think there's much difference from the regular client and the UWP one? appears setting the channel as zlive works when trying to load roblox, however it switches back instantly to 64bit after launching.
