### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Shigetorum635** [bituq/Roshade#5]
How to replicate:

1. Download the latest installer from the website.
2. Extract to desktop and run as administrator
3. Roblox reinstalls sucessfully and error appears.

Images:

![image](https://user-images.githubusercontent.com/48862659/129488375-7bbcaec9-d12b-4739-aa4b-9f5131934f8e.png)
![image](https://user-images.githubusercontent.com/48862659/129488387-4bae8193-0bc4-4b1f-8f04-e9c1c8eb6245.png)
![image](https://user-images.githubusercontent.com/48862659/129488393-f65e5514-1a57-4272-b728-ac706fb6a905.png)

Before I had gotten also a roshade.dll missing error.

System: Windows 10 64 Bit

Specs:

Ryzen 5 2600 6 Cores, 12 threads
GTX 1650 4GB
8GB RAM

No idea whats happening

**Comment by Schwiftyyyyy** [comment]
This is also happening with me.

**Comment by ChaoS-0515** [comment]
The person who made this is just lazy and doesn't care. Just use something else as this has a pretty high chance of never being fixed.

**Comment by diondestroyer2134** [comment]
Same here. I don't know what I'm doing wrong. I am following Zeal's instructions, but it'll still give me errors.

**Comment by jgentil** [comment]
Was Roblox running when you installed it?  That could  very likely be the problem.

**Comment by Shigetorum635** [comment]
> Was Roblox running when you installed it? That could very likely be the problem.

From the error messages it doesnt portray that could be an issue. As roblox running cannot interfere with new files being added to the folder.

If a file being used by roblox is deleted. Then yes, it would make sense for it to error, but here it is only trying to read.

**Comment by bituq** [comment]
This issue is likely due to the Roblox directory being located in a folder other than %localappdata% (such as %programfiles(x86)%.

Try to check where the Roblox directory is located. If it's located in anywhere other than localappdata, place it there.

**Comment by KirbyCooter** [comment]
> How to replicate:
> 
> 1. Download the latest installer from the website.
> 2. Extract to desktop and run as administrator
> 3. Roblox reinstalls sucessfully and error appears.
> 
> Images:
> 
> ![image](https://user-images.githubusercontent.com/48862659/129488375-7bbcaec9-d12b-4739-aa4b-9f5131934f8e.png) ![image](https://user-images.githubusercontent.com/48862659/129488387-4bae8193-0bc4-4b1f-8f04-e9c1c8eb6245.png) ![image](https://user-images.githubusercontent.com/48862659/129488393-f65e5514-1a57-4272-b728-ac706fb6a905.png)
> 
> Before I had gotten also a roshade.dll missing error.
> 
> System: Windows 10 64 Bit
> 
> Specs:
> 
> Ryzen 5 2600 6 Cores, 12 threads GTX 1650 4GB 8GB RAM
> 
> No idea whats happening

Sorry for being late, but make sure when installing RoShade,

1. You have ROBLOX uninstalled already. ( so it cant have the problem with x86 )
2. Let ROBLOX be installed by RoShade.
3. Then click "OK" on the ROBLOX popup so it closes.
4. Let it install, have fun!

**Comment by bituq** [comment]
Closing this issue because it was fixed in the latest update (v1.4.0)
