### ISSUE TITLE
Firefox isn't able to visit the download link.

### ISSUE THREAD

**Issue by ItzVaio** [bituq/Roshade#7]
Im trying to install RoShade for my low-end PC, but firefox just won't even go to the download link.
And it will later show "Download error"

Is there a fix, because im using the actual website.

**Comment by aaronliu0130** [comment]
use the download from releases

**Comment by bituq** [comment]
You can find the latest releases [here](https://github.com/bituq/Roshade/releases), so you can bypass the website.
