### ISSUE TITLE
[REQ] Download 2.0.0 Release Through GitHub.

### ISSUE THREAD

**Issue by aaronliu0130** [bituq/Roshade#8]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when sites direct you to Google Drive to download.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Ex. I want to download through GitHub releases.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. Ex. We could just nuke Google, but that won't work.

**Additional context**
Add any other context or screenshots about the feature request here. Ex. Alan, please add details.

**Comment by aaronliu0130** [comment]
How is this completed? I don't see a new release.

**Comment by lynutodev** [comment]
beacuse he doesnt want people making a custom one lol

**Comment by aaronliu0130** [comment]
What do you mean making a custom one?

**Comment by lynutodev** [comment]
he doesnt want people having code i dont think

**Comment by aaronliu0130** [comment]
The code is literally in the repository
